
import __ASTRO_IMAGE_IMPORT_pIHLg from "../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fomscs-review-dl.mdx";
import __ASTRO_IMAGE_IMPORT_IkSem from "../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fomscs-review-ml.mdx";
import __ASTRO_IMAGE_IMPORT_Z1f3AuW from "../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fomscs-review-sdp.mdx";
import __ASTRO_IMAGE_IMPORT_1aYsBj from "../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fomscs-review-ml4t.mdx";
import __ASTRO_IMAGE_IMPORT_1Q07nD from "../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fuser-dev-spectrum.mdx";
import __ASTRO_IMAGE_IMPORT_BaK7O from "../../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fold-blogs%2Fold-blogs.mdx";
import __ASTRO_IMAGE_IMPORT_1r8eoP from "../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fomscs-review-ns.mdx";
import __ASTRO_IMAGE_IMPORT_Z1c8naH from "../../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FfieldNotes%2Fstinkhorns-modoc%2Fstinkhorns-modoc.mdx";
export default new Map([["../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fomscs-review-dl.mdx", __ASTRO_IMAGE_IMPORT_pIHLg], ["../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fomscs-review-ml.mdx", __ASTRO_IMAGE_IMPORT_IkSem], ["../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fomscs-review-sdp.mdx", __ASTRO_IMAGE_IMPORT_Z1f3AuW], ["../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fomscs-review-ml4t.mdx", __ASTRO_IMAGE_IMPORT_1aYsBj], ["../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fuser-dev-spectrum.mdx", __ASTRO_IMAGE_IMPORT_1Q07nD], ["../../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fold-blogs%2Fold-blogs.mdx", __ASTRO_IMAGE_IMPORT_BaK7O], ["../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fomscs-review-ns.mdx", __ASTRO_IMAGE_IMPORT_1r8eoP], ["../../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FfieldNotes%2Fstinkhorns-modoc%2Fstinkhorns-modoc.mdx", __ASTRO_IMAGE_IMPORT_Z1c8naH]]);
		